name: Build and Push Overleaf (AVX-safe TL2023)

on:
  push:
    branches: [ main, wip ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      # Show live build logs instead of the “quiet” default
      BUILDKIT_PROGRESS: plain
      # Prevent log truncation on long steps
      BUILDKIT_STEP_LOG_MAX_SIZE: "10485760"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional (recommended if Docker Hub pulls rate-limit you)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push (with cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          build-args: |
            TL_MIRROR=http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2023/tlnet-final